OPS-1361 Add IPSets to block requests from malicious IPs, and a lambda that updates these lists hourly
juiceinc/terraform-aws-juiceinc-waf pull request #1
Opened 2018-11-02 21:29 UTC by cwire4

Ticket: [OPS-1361](https://juiceanalytics.atlassian.net/browse/OPS-1361)
Type: Improvement/Security

#### This PR introduces the following changes

- Adds IP blocking rules to the existing WebACL
- Adds a lambda function that works together with a cloudwatch event and event target to update the lists hourly.

- [x] Add information to the release notes documentation
- [x] Add new feature to the usage documentation

2018-11-06 20:54 UTC, radix commented
Is WAFIPLambda.zip meant to be committed to version control?

2018-11-06 20:59 UTC, radix requested changes
* WAFIPLambda/LICENSE.txt should either be removed or have real content added to it, I guess?

2018-11-06 22:55 UTC, cwire4 commented
Yeah, I meant to include the packaged version so it should just work when someone pulls the new version and they don't have to repackage it if they don't want to make modifications.  I didn't realize I left the License empty, it was supposed to be the original one in the AWS repo.  Adrienne and I read through it and we thought we'd be ok to redistribute it here as long as the license was included.

I updated the license and repackaged the ZIP to include it as well.

2018-11-08 15:10 UTC, radix approved these changes

2018-11-08 15:12 UTC, merged